services:
  db:
    image: docker.io/library/postgres:18
    container_name: emergency-location-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql
    secrets:
      - db_password

  backend:
    image: docker.io/smilekundev/emergency-location:latest
    container_name: backend
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - env/.env.template
      - env/.env
      - env/.env.prod
    secrets:
      - db_password

secrets:
  db_password:
    file: secrets/db_password.txt

volumes:
  db_data:
    name: emergency_location_postgres_data