name: Hello World Pipeline

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo 'Hello World'
      - name: Execute Multiline
        run: |
          pwd
          ls -la
          whoami
