class InvalidPhoneFormatError(Exception): ...


class NotFoundError(Exception): ...


class SmsSendError(Exception): ...


class WhatsAppSendError(Exception): ...


class InvalidImageError(Exception): ...
